In [2]:
import numpy as np

In [3]:
d1 = np.array([1, 2, 3, 4, 5])
d1.ndim

1

In [4]:
d2 = np.array([[ 10, 20, 30, 40, 50],
               [60, 70, 80, 90, 99]])
d2.ndim


2

In [5]:
d3 = np.array([[[ 100, 200, 300, 400, 500],
                [600, 700, 800, 900, 999],
                [ 111, 222, 333, 444, 555]]])
d3.ndim

3

In [6]:
d1.shape, d1.ndim, d1.dtype, d1.size, 

((5,), 1, dtype('int64'), 5)

In [7]:
d2.shape, d2.ndim, d2.dtype, d2.size, 

((2, 5), 2, dtype('int64'), 10)

In [8]:
d3.shape, d3.ndim, d3.dtype, d3.size, 

((1, 3, 5), 3, dtype('int64'), 15)

In [9]:
import pandas as pd

In [12]:
a1 = pd.DataFrame(d1)
a1

,0
0,1
1,2
2,3
3,4
4,5


In [14]:
d1

array([1, 2, 3, 4, 5])

In [17]:
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [22]:
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
array = np.arange(0,100,3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [27]:
random_array = np.random.randint(0,10, size = (7,2)) 
random_array

array([[9, 7],
       [0, 0],
       [0, 9],
       [4, 1],
       [1, 3],
       [4, 9],
       [6, 3]], dtype=int32)

In [33]:
randomarray = np.random.random((3,5))
randomarray

array([[0.81380075, 0.04029997, 0.7882954 , 0.64914082, 0.27673793],
       [0.11586215, 0.31654299, 0.71424087, 0.59517061, 0.12645308],
       [0.60550751, 0.38748143, 0.35945031, 0.57300511, 0.22200694]])

In [51]:
np.random.seed(42)
random_num = np.random.randint(0,10, size =(4,6))
random_num

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

In [53]:
Lalala = np.random.randint(1,10, size=(3,7))
Lalala

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]], dtype=int32)

In [55]:
unique_nums = np.unique(Lalala)
print("Array:\n", Lalala)
print("\nUnique numbers:\n", unique_nums)

Array:
 [[7 8 3 1 4 2 8]
 [4 2 6 6 4 6 2]
 [2 4 8 7 9 8 5]]

Unique numbers:
 [1 2 3 4 5 6 7 8 9]


In [61]:
unique_nums

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [78]:
Lalala[:2 ,:2]

array([[7, 8],
       [4, 2]], dtype=int32)

In [67]:
 Lalala

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2],
       [2, 4, 8, 7, 9, 8, 5]], dtype=int32)